### ISSUE TITLE
Fix deployment

### ISSUE THREAD

**Issue by JonasSchaub** [JonasSchaub/ART2a-Clustering-for-Java#13]
There seems to be a problem with the fixed(?) Java version in build.gradle

**Comment by ZeynepDagtekin** [comment]
I received an Error: "org.gradle.jvm.toolchain.internal.ToolchainDownloadFailedException: No locally installed toolchains match and toolchain download repositories have not been configured."
It could be fixed by commenting out line 47-53.
However, after that the Error: "> Could not get unknown property 'javadocJar' for object of type org.gradle.api.internal.artifacts.dsl.DefaultArtifactHandler." occured
Which then was fixed by commenting out line 125-127. 
I also tried changing the JDK version to a more recent one but it did not change anything.

**Comment by JonasSchaub** [comment]
@ZeynepDagtekin are you still able to reproduce the error? If so, could you please switch to branch https://github.com/JonasSchaub/ART2a-Clustering-for-Java/tree/issues-11-13-build and see whether it is fixed there? If you cannot reproduce the error anymore in your local environment (as I think you said yesterday), we can ask Max to test it, maybe.

**Comment by ZeynepDagtekin** [comment]
So, yesterday I changed the JDK version back to what I originally had it set to and the errors went away, that's why I thought it works again. However, after I reloaded the build, I got the same issues.

**Comment by ZeynepDagtekin** [comment]
I seem to have the same issue on that branch as well.

**Comment by JonasSchaub** [comment]
With what JDK version are you getting the error? Java 17 should make no issues here.

**Comment by JonasSchaub** [comment]
I have tried something else on the same branch, could you test again?

**Comment by ZeynepDagtekin** [comment]
I got the error with Java 21, I changed it to Java 17 and it worked this time. 
I tested again and switched back to Java 21 and it seems to work now?

**Comment by JonasSchaub** [comment]
> I tested again and switched back to Java 21 and it seems to work now?

Does it work or does it not work? :D 
I've added a plugin that automatically downloads the required Java toolchain if there is none locally available.
